; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter =
	+<*>
	-<host/>
build_flags =
	-std=gnu++17
test_build_src = yes
test_ignore = host/*
lib_deps =
	adafruit/Adafruit_VL53L0X@1.2.2


[env:host]
platform = native
build_flags =
	-std=gnu++17
build_src_filter =
	+<*>
	-<driver/>
	-<hal/>
	-<main.cpp>
test_build_src = yes
debug_server = C:\msys64\mingw64\bin\gdb
test_ignore = target/*
test_framework = unity
build_type = debug
debug_test = host/unit/test_loop_app
debug_build_flags =
	-g              		# Gera informação de debug
    -ggdb3          		# Símbolos de debug completos
    -O0             		# Sem otimização para debug
    -fno-omit-frame-pointer # Facilita stack traces