; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter =
	+<*>
	-<host/>
build_flags =
	-L src
	-std=gnu++17
test_build_src = yes
lib_deps =
	adafruit/Adafruit_VL53L0X@1.2.2


[env:host]
platform = native
build_type = debug
build_flags =
	-I test/mocks
	-L src
	-std=gnu++17
	-Wl,-subsystem,console
build_src_filter =
	+<*>
	-<driver/>
	-<hal/>
	-<main.cpp>
test_build_src = yes
test_filter = host/*
test_framework = unity
debug_test = host/unit/test_filter
debug_build_flags =
	-g              		# Gera informação de debug
    -ggdb3          		# Símbolos de debug completos
    -O0             		# Sem otimização para debug
    -fno-omit-frame-pointer # Facilita stack traces